ptファイルをいつものcsvに変換

In [2]:
import pandas as pd 
import numpy as np 
import torch

In [3]:
pt_path = '/Users/matsunagatakahiro/Desktop/res2025/ActFormer/toy_data_generation/node_features_matrix.pt'
loaded_tensor = torch.load(pt_path)
print(loaded_tensor) # 特徴量行列．idは排除

tensor([[0.5000, 1.0000],
        [0.4000, 0.0000],
        [0.2000, 1.0000],
        [0.0000, 0.0000],
        [0.6000, 1.0000],
        [0.5000, 0.0000],
        [0.4000, 1.0000],
        [0.2000, 0.0000],
        [0.8000, 1.0000],
        [0.6000, 0.0000],
        [0.5000, 1.0000],
        [0.4000, 0.0000],
        [1.0000, 1.0000],
        [0.8000, 0.0000],
        [0.6000, 1.0000],
        [0.5000, 0.0000]])


In [4]:
csv_path = '/Users/matsunagatakahiro/Desktop/res2025/ActFormer/toyact_gen/input/node.csv'
df = pd.read_csv(csv_path)
df_pt = torch.tensor(df.values)
print(df_pt)

tensor([[0, 0, 0, 1, 0, 0],
        [1, 1, 0, 0, 1, 0],
        [2, 1, 0, 0, 0, 1],
        [3, 0, 1, 0, 1, 1]])


In [5]:
df = pd.read_csv(csv_path)
print(df)

   nodeid  work  shop  leisure  x  y
0       0     0     0        1  0  0
1       1     1     0        0  1  0
2       2     1     0        0  0  1
3       3     0     1        0  1  1


In [6]:
adj_path = '/Users/matsunagatakahiro/Desktop/res2025/ActFormer/toy_data_generation/grid_adjacency_matrix.pt'
loaded_tensor = torch.load(adj_path)
print(loaded_tensor) # 隣接行列．idは排除
print(loaded_tensor.shape) # (n_nodes, n_nodes)

tensor([[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]], dtype=torch.int32)
torch.Size([16, 16])


In [6]:
testnp = np.zeros(4)
print(testnp)

[0. 0. 0. 0.]


In [7]:
testnp[3] = 1
print(testnp)

[0. 0. 0. 1.]
