In [184]:
import numpy as np
import pandas as pd 
import torch

from utils.logger import logger

In [30]:
class Network:
    def __init__(self, adj_matrix, node_features):
        logger.info('Network init')
        self.adj_matrix = adj_matrix
        self.node_features = node_features
        # self.df_penalty = df_penalty

        self.N = len(self.adj_matrix)
        self.node_id_list = [i for i in range(self.N)]

        #効用関数に入れる変数の行列を作成する
        # 説明変数4つの行列を挿入する
        self.feature_mat_0 = self._node_feature_matrix(feature_num = 0) 
        self.feature_mat_1 = self._node_feature_matrix(feature_num = 1)
        self.feature_mat_2 = self._node_feature_matrix(feature_num = 3)
        self.feature_mat_3 = self._node_feature_matrix(feature_num = 3)

    def _node_feature_matrix(self, feature_num):
        part_feature_mat = np.zeros((self.N, self.N))
        feature_vec = self.node_features[:, feature_num]
        for j in range(self.N): # 移動先がアーケードあるか
            part_feature_mat[j, :] = feature_vec 

        feature_mat = np.tile(part_feature_mat, (1, 1)).reshape((self.N, self.N))
        return feature_mat

In [193]:
adj_matrix = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/grid_adjacency_matrix.pt")
node_features = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/node_features_matrix.pt")
demand =  pd.read_csv("demand.csv", index_col = 0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [194]:
node_features

tensor([[0.6312, 0.0977, 0.3765, 0.3169],
        [0.9774, 0.2286, 0.9109, 0.2096],
        [0.9220, 0.1256, 0.6988, 0.1225],
        [0.7407, 0.1779, 0.5745, 0.5193],
        [0.4786, 0.7803, 0.0857, 0.2556],
        [0.5141, 0.8676, 0.0985, 0.6453],
        [0.2561, 0.4009, 0.1321, 0.2452],
        [0.7980, 0.3953, 0.8843, 0.5611],
        [0.3329, 0.9774, 0.1872, 0.8133],
        [0.0730, 0.7013, 0.8024, 0.2411],
        [0.7193, 0.2770, 0.5377, 0.9791],
        [0.5923, 0.9338, 0.6048, 0.0874],
        [0.7359, 0.7856, 0.3321, 0.9855],
        [0.0626, 0.9215, 0.8099, 0.4877],
        [0.2037, 0.7731, 0.9712, 0.3734],
        [0.6298, 0.4996, 0.8380, 0.8753]])

In [27]:
network = Network(adj_matrix, node_features)

[I 241202 17:14:26 512302903:3] Network init


In [28]:
network.feature_mat

array([[0.63122934, 0.9774121 , 0.92196339, 0.74066287, 0.47862303,
        0.51410985, 0.25613952, 0.79801083, 0.3328948 , 0.07297444,
        0.71927392, 0.59228796, 0.7359249 , 0.062603  , 0.20371342,
        0.62980473],
       [0.63122934, 0.9774121 , 0.92196339, 0.74066287, 0.47862303,
        0.51410985, 0.25613952, 0.79801083, 0.3328948 , 0.07297444,
        0.71927392, 0.59228796, 0.7359249 , 0.062603  , 0.20371342,
        0.62980473],
       [0.63122934, 0.9774121 , 0.92196339, 0.74066287, 0.47862303,
        0.51410985, 0.25613952, 0.79801083, 0.3328948 , 0.07297444,
        0.71927392, 0.59228796, 0.7359249 , 0.062603  , 0.20371342,
        0.62980473],
       [0.63122934, 0.9774121 , 0.92196339, 0.74066287, 0.47862303,
        0.51410985, 0.25613952, 0.79801083, 0.3328948 , 0.07297444,
        0.71927392, 0.59228796, 0.7359249 , 0.062603  , 0.20371342,
        0.62980473],
       [0.63122934, 0.9774121 , 0.92196339, 0.74066287, 0.47862303,
        0.51410985, 0.25613952, 

In [31]:
adj_matrix

tensor([[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]], dtype=torch.int32)

In [221]:
import torch
import pandas as pd
import numpy as np
from utils.logger import logger

class Network:
    def __init__(self, adj_matrix, node_features):
        logger.info('Network init')
        self.adj_matrix = adj_matrix
        self.node_features = node_features
        # self.df_penalty = df_penalty

        self.N = len(self.adj_matrix)
        self.node_id_list = [i for i in range(self.N)]

        #効用関数に入れる変数の行列を作成する
        # 説明変数4つの行列を挿入する
        self.feature_mat_0 = self._node_feature_matrix(feature_num = 0) 
        self.feature_mat_1 = self._node_feature_matrix(feature_num = 1)
        self.feature_mat_2 = self._node_feature_matrix(feature_num = 3)
        self.feature_mat_3 = self._node_feature_matrix(feature_num = 3)

    def _node_feature_matrix(self, feature_num):
        part_feature_mat = np.zeros((self.N, self.N))
        feature_vec = self.node_features[:, feature_num]
        for j in range(self.N): # 移動先がアーケードあるか
            part_feature_mat[j, :] = feature_vec 

        feature_mat = np.tile(part_feature_mat, (1, 1)).reshape((self.N, self.N))
        return feature_mat
    
class RecursiveLogit:
    def __init__(self, network, demand, discount_rate, T, device):
        self.network = network # ネットワーク
        self.demand = demand
        self.N_OD = len(demand)
        self.discount_rate = discount_rate  # 割引率
        self.T = T  # RLの時間ステップ数
        self.device = device  # 設備を指定 (CPU or GPU)
    def _Mset(self, x): # 時間ごと即時効用を計算する
        '''
        inst = np.zeros((self.T, self.network.N, self.network.N))
        for t in range(self.T): 
            inst_t = (
                self.network.feature_mat_0[:, :] * x[0]
                + self.network.feature_mat_1[:, :] * x[1]
                + self.network.feature_mat_2[:, :] * x[2]
                + self.network.feature_mat_3[:, :] * x[3]
                )
            inst[t, :, :] = inst_t
        '''
        feature_mat_0 = torch.tensor(self.network.feature_mat_0, device=self.device, dtype=torch.float32)
        feature_mat_1 = torch.tensor(self.network.feature_mat_1, device=self.device, dtype=torch.float32)
        feature_mat_2 = torch.tensor(self.network.feature_mat_2, device=self.device, dtype=torch.float32)
        feature_mat_3 = torch.tensor(self.network.feature_mat_3, device=self.device, dtype=torch.float32)
        inst = feature_mat_0 * x[0] + feature_mat_1 * x[1] + feature_mat_2 * x[2] + feature_mat_3 * x[3]
        inst = inst.unsqueeze(0).repeat(self.T, 1, 1)
        return inst
    
    def newPall(self, x):
        '''
        選択確率の計算
        '''
        beta = self.discount_rate
        Pall = torch.zeros((self.N_OD, self.T, self.network.N, self.network.N), device=self.device)

        Mts = self._Mset(x)
        M = torch.exp(Mts)
        #隣接しているもの以外の即時効用を0にする
        adj_matrix_expanded = self.network.adj_matrix.unsqueeze(0)
        M = M * adj_matrix_expanded

        for od in range(self.N_OD):
            d = self.demand[od, 1]
            z = torch.zeros((self.T + 1, self.network.N), device=self.device)  # 状態数は遷移数Tから1多いのでT+1
            #最後の状態ではdのみが1で他が0
            z[self.T, d] = 1

            d_mat = torch.ones((self.network.N, self.network.N), device=self.device)
            d_mat[d, :] = 0
            d_mat[d, d] = 1
            #目的地dからはdにしかいけないようにする
            M_d = M * d_mat
            
            for t in range(self.T, 0, -1):
                zii = M_d[t - 1] * (z[t].view(1, -1) ** beta)
                zi = zii.sum(axis=1)
                z[t - 1] =zi
                #z[t - 1] = (zi == 0) * 1 + (zi != 0) * zi

            for t in range(self.T):
                transition_prob = torch.exp(torch.log(M_d[t]) + beta * torch.log(z[t + 1].view(1, -1)) - torch.log(z[t].view(-1, 1)))
                #Pall[od, t] = transition_prob
                Pall[od, t] = torch.where(transition_prob >= 1, torch.ones_like(transition_prob), transition_prob)

                if (transition_prob > 1).any():
                    logger.error(f'od={od}, t={t}')
                    logger.error(f'M={M[t]}, z+={z[t + 1]}, z- = {z[t]}')
                if (transition_prob < 0).any():
                    logger.error(f'od={od}, t={t}')
                    logger.error(f'M={M[t]}, z+={z[t + 1]}, z- = {z[t]}')
        return Pall

    def simulation(self, x):
        Pall = self.newPall(x)
        df = pd.DataFrame(columns = [str(i) for i in range(self.T + 1)])
        for od in range(self.N_OD):
            o = self.demand[od, 0]
            simulation_num = self.demand[od, 2]
            simulation_result_tensor = torch.zeros((simulation_num, self.T + 1), device=self.device)
            for i in range(simulation_num):
                current_node = o
                simulation_result_tensor[i, 0] = current_node
                for t in range(self.T):
                    prob = Pall[od, t, current_node, :]
                    if prob.sum() <= 0:
                        logger.error(f'od={od}, t={t}, current_node={current_node}')
                        logger.error(f'Pall={Pall[od, t]}')
                    next_node = torch.multinomial(prob, 1).item()
                    simulation_result_tensor[i, t+1] = next_node
                    current_node = next_node
            result_df = pd.DataFrame(simulation_result_tensor.cpu().numpy(), columns = [str(i) for i in range(self.T + 1)])
            df = pd.concat([df, result_df])
        return df

In [222]:
adj_matrix = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/grid_adjacency_matrix.pt")
node_features = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/node_features_matrix.pt")
demand =  pd.read_csv("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/demand.csv", index_col = 0)
demand = torch.tensor(demand.values, dtype=torch.long)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#demand = demand[1].unsqueeze(0)

In [223]:
indices = torch.arange(len(adj_matrix))
adj_matrix[indices, indices] = 1

In [224]:
network = Network(adj_matrix, node_features)
rl = RecursiveLogit(network, demand, 0.9, 10, device)

[I 241203 17:42:08 1949470591:8] Network init


In [225]:
Pall= rl.newPall([0.1, 0.2, 0.3, 0.4])

[E 241203 17:42:09 1949470591:97] od=0, t=2
[E 241203 17:42:09 1949470591:98] M=tensor([[1.3559, 1.3366, 0.0000, 0.0000, 1.4665, 0.0000, 0.0000, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [1.3559, 1.3366, 1.2251, 0.0000, 0.0000, 1.9672, 0.0000, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 1.3366, 1.2251, 1.6050, 0.0000, 0.0000, 1.3197, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 1.2251, 1.6050, 0.0000, 0.0000, 0.0000, 1.7361, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [1.3559, 0.0000, 0.0000, 0.0000, 1.4665, 1.9672, 0.0000, 0.0000, 2.2213,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 1.3366, 0.0000, 0.0000, 1.4665, 1.9672, 1.3197, 0.0000, 0.0000,
             1.3721, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0

In [226]:
df= rl.simulation([0.1, 0.2, 0.3, 0.4])

[E 241203 17:42:09 1949470591:97] od=0, t=2
[E 241203 17:42:09 1949470591:98] M=tensor([[1.3559, 1.3366, 0.0000, 0.0000, 1.4665, 0.0000, 0.0000, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [1.3559, 1.3366, 1.2251, 0.0000, 0.0000, 1.9672, 0.0000, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 1.3366, 1.2251, 1.6050, 0.0000, 0.0000, 1.3197, 0.0000, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 1.2251, 1.6050, 0.0000, 0.0000, 0.0000, 1.7361, 0.0000,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [1.3559, 0.0000, 0.0000, 0.0000, 1.4665, 1.9672, 0.0000, 0.0000, 2.2213,
             0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
            [0.0000, 1.3366, 0.0000, 0.0000, 1.4665, 1.9672, 1.3197, 0.0000, 0.0000,
             1.3721, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0

# 対数尤度の計算

In [237]:
import torch
import pandas as pd
import numpy as np
from utils.logger import logger
import importlib

from network import Network
from Recursive import RecursiveLogit
from optimize import GPUOptimizer

In [238]:
import sys
import importlib

# 依存モジュールと対象モジュールを削除
for mod in ['network', 'Recursive', 'optimize']:
    if mod in sys.modules:
        del sys.modules[mod]

# 再インポート
import network
import Recursive
import optimize

# 必要なら再度クラスをインポート
from network import Network
from Recursive import RecursiveLogit
from optimize import GPUOptimizer


In [239]:
adj_matrix = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/grid_adjacency_matrix.pt")
node_features = torch.load("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/node_features_matrix.pt")
demand =  pd.read_csv("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/demand.csv", index_col = 0)
trip_df = pd.read_csv("/Users/kurasawaryuuhei/Desktop/10_修論/code/transformer/data_generation/route_data/route.csv", index_col = 0)
demand = torch.tensor(demand.values, dtype=torch.long)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [240]:
x_dim = 4
x00 = np.zeros(x_dim) 
bounds = [(-500, 500) for _ in range(x_dim)]
network = Network(adj_matrix, node_features)
rl = RecursiveLogit(network, demand, 1, 10, device)
optimizer = GPUOptimizer(network, trip_df, rl, bounds, x00, demand)

[I 241204 09:21:25 network:9] Network init
[I 241204 09:21:25 optimize:11] Optimizer init


In [241]:
optimizer._loglikelihood([0, 0, 0, 0])

[I 241204 09:21:26 optimize:112] x=[0, 0, 0, 0], LL=-52183.95703125


tensor(-52183.9570)

In [242]:
optimizer._loglikelihood([0.1, 0.2, 0.3, 0.4])

[I 241204 09:21:27 optimize:112] x=[0.1, 0.2, 0.3, 0.4], LL=-51643.015625


tensor(-51643.0156)

In [243]:
x_opt, LL0, LL_res, rho2, rho2_adj, tval_res = optimizer.optimize()

[I 241204 09:21:29 optimize:47] Optimizer optimize start
[I 241204 09:21:29 optimize:112] x=Parameter containing:
    tensor([0., 0., 0., 0.], requires_grad=True), LL=-52183.95703125
[I 241204 09:21:29 optimize:58] x.grad: tensor([ 1131.0800, -1427.3850, -1333.1852, -1397.9734])
[I 241204 09:21:29 optimize:112] x=Parameter containing:
    tensor([-0.2138,  0.2698,  0.2520,  0.2643], requires_grad=True), LL=-52043.16015625
[I 241204 09:21:29 optimize:58] x.grad: tensor([-2154.3481,  2012.3347,   -55.1542,    94.5581])
[I 241204 09:21:29 optimize:112] x=Parameter containing:
    tensor([-0.0775,  0.1333,  0.2219,  0.2250], requires_grad=True), LL=-51709.44921875
[I 241204 09:21:30 optimize:58] x.grad: tensor([-502.9149,  276.0088, -237.5115, -359.5654])
[I 241204 09:21:30 optimize:112] x=Parameter containing:
    tensor([-0.0317,  0.1123,  0.2562,  0.2710], requires_grad=True), LL=-51672.29296875
[I 241204 09:21:30 optimize:58] x.grad: tensor([-141.0915, -103.8464,  -33.2539, -330.7846])

In [245]:
tval_res

array([ 3.770638,  9.056898, 21.32271 , 20.75206 ], dtype=float32)

In [235]:
hess = optimizer.hessian(x_opt)

[I 241204 09:20:45 optimize:112] x=tensor([0.0830, 0.1911, 0.2852, 0.3788], grad_fn=<ViewBackward0>), LL=-51641.69921875


In [236]:
np.linalg.inv(hess)

array([[ 4.8502386e-04,  3.7606608e-04,  6.5579494e-05,  1.5622805e-05],
       [ 3.7606654e-04,  4.4503936e-04,  7.2969269e-05, -6.8958732e-05],
       [ 6.5581014e-05,  7.2970557e-05,  1.7894687e-04,  2.0103935e-05],
       [ 1.5626245e-05, -6.8955662e-05,  2.0104781e-05,  3.3321089e-04]],
      dtype=float32)

In [2]:
import pandas as pd
demand =  pd.read_csv("demand.csv", index_col = 0)

In [4]:
demand.values[0]

array([   0,   15, 1000])

In [23]:
import pandas as pd
route =  pd.read_csv("route_data/route.csv", index_col = 0)

In [ ]:
len(route[route['8'] == 16])

1